import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import prettierConfig from 'eslint-config-prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  prettierConfig,
  {
    // next-env.d.ts is regenerated by Next on every build and explicitly
    // says not to edit it — its triple-slash references are intentional.
    ignores: ['.next/**', 'node_modules/**', 'public/**', 'supabase/**', 'next-env.d.ts'],
  },
];

export default eslintConfig;
