import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import prettierConfig from 'eslint-config-prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  prettierConfig,
  {
    // next-env.d.ts is regenerated by Next on every build and explicitly
    // says not to edit it — its triple-slash references are intentional.
    //
    // playwright.local.ts is the throwaway config CLAUDE.md tells you to write
    // to run the suite against this sandbox's older browsers. It's gitignored,
    // but eslint reads the working tree rather than the index, so without this
    // the documented workflow leaves a warning in every `npm run check`.
    ignores: [
      '.next/**',
      'node_modules/**',
      'public/**',
      'supabase/**',
      'next-env.d.ts',
      'playwright.local.ts',
    ],
  },
];

export default eslintConfig;
